dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/link?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root


rules:
  - !SHARDING
    tables:
      t_user:
        actualDataNodes: ds_0.t_user_${0..15}
        tableStrategy: # 分表策略
          # 用于单分片键的标准分片场景
          standard:
            shardingColumn: username # 分片键
            shardingAlgorithmName: user_table_hash_mod # 分片算法，对应 rules[0].shardingAlgorithms
    shardingAlgorithms:
      user_table_hash_mod:
        type: hash_mod
        props: #f 分片数量
          sharding-count: 16

props:
  sql-show: true